import "./globals.css"
import { ToastContainer, Zoom } from "react-toastify"
import "react-toastify/dist/ReactToastify.css"

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        
        {children}
        <ToastContainer
          position="bottom-center"
          hideProgressBar={true}
          draggable
          closeButton={false}
          stacked={true}
          transition={Zoom}
          autoClose={false}
        />
      </body>
    </html>
  )
}
