import "./globals.css"
import Link from "next/link"
import { ToastContainer, Zoom } from "react-toastify"
import "react-toastify/dist/ReactToastify.css"

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <header>
          <nav>
            <ul className="flex justify-center gap-16">
              
            </ul>
          </nav>
        </header>
        {children}
        <ToastContainer
          position="bottom-center"
          hideProgressBar={true}
          draggable
          closeButton={false}
          stacked={true}
          transition={Zoom}
          autoClose={false}
        />
      </body>
    </html>
  )
}
